-- Insert Bed Bank Amenities (stored procedure does dup checking)
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'2', @LanguageCode='EN', @Description='24-hour room service', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'3', @LanguageCode='EN', @Description='24-hour security', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'4', @LanguageCode='EN', @Description='Adjoining rooms', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'5', @LanguageCode='EN', @Description='Air conditioning', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'6', @LanguageCode='EN', @Description='Airline desk', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'7', @LanguageCode='EN', @Description='ATM/Cash machine', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'8', @LanguageCode='EN', @Description='Baby sitting', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'9', @LanguageCode='EN', @Description='BBQ/Picnic area', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'10', @LanguageCode='EN', @Description='Bilingual staff', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'11', @LanguageCode='EN', @Description='Bookstore', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'12', @LanguageCode='EN', @Description='Boutiques/stores', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'13', @LanguageCode='EN', @Description='Brailed elevators', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'14', @LanguageCode='EN', @Description='Business library', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'15', @LanguageCode='EN', @Description='Car rental desk', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'16', @LanguageCode='EN', @Description='Casino', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'17', @LanguageCode='EN', @Description='Check cashing policy', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'18', @LanguageCode='EN', @Description='Check-in kiosk', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'19', @LanguageCode='EN', @Description='Cocktail lounge', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'20', @LanguageCode='EN', @Description='Coffee shop', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'21', @LanguageCode='EN', @Description='Coin operated laundry', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'22', @LanguageCode='EN', @Description='Concierge desk', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'23', @LanguageCode='EN', @Description='Concierge floor', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'24', @LanguageCode='EN', @Description='Conference facilities', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'25', @LanguageCode='EN', @Description='Courtyard', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'26', @LanguageCode='EN', @Description='Currency exchange', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'27', @LanguageCode='EN', @Description='Desk with electrical outlet', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'28', @LanguageCode='EN', @Description='Doctor on call', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'29', @LanguageCode='EN', @Description='Door man', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'30', @LanguageCode='EN', @Description='Driving range', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'31', @LanguageCode='EN', @Description='Drugstore/pharmacy', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'32', @LanguageCode='EN', @Description='Duty free shop', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'33', @LanguageCode='EN', @Description='Elevators', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'34', @LanguageCode='EN', @Description='Executive floor', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'35', @LanguageCode='EN', @Description='Exercise gym', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'36', @LanguageCode='EN', @Description='Express check-in', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'37', @LanguageCode='EN', @Description='Express check-out', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'38', @LanguageCode='EN', @Description='Family plan', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'39', @LanguageCode='EN', @Description='Florist', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'40', @LanguageCode='EN', @Description='Folios', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'41', @LanguageCode='EN', @Description='Free airport shuttle', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'42', @LanguageCode='EN', @Description='Free parking', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'43', @LanguageCode='EN', @Description='Free transportation', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'44', @LanguageCode='EN', @Description='Game room', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'45', @LanguageCode='EN', @Description='Gift/News stand', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'46', @LanguageCode='EN', @Description='Hairdresser/barber', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'47', @LanguageCode='EN', @Description='Accessible facilities', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'48', @LanguageCode='EN', @Description='Health club', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'49', @LanguageCode='EN', @Description='Heated pool', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'50', @LanguageCode='EN', @Description='Housekeeping - daily', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'51', @LanguageCode='EN', @Description='Housekeeping - weekly', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'52', @LanguageCode='EN', @Description='Ice machine', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'53', @LanguageCode='EN', @Description='Indoor parking', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'54', @LanguageCode='EN', @Description='Indoor pool', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'55', @LanguageCode='EN', @Description='Jacuzzi', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'56', @LanguageCode='EN', @Description='Jogging track', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'57', @LanguageCode='EN', @Description='Kennels', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'58', @LanguageCode='EN', @Description='Laundry/Valet service', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'59', @LanguageCode='EN', @Description='Liquor store', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'60', @LanguageCode='EN', @Description='Live entertainment', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'61', @LanguageCode='EN', @Description='Massage services', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'62', @LanguageCode='EN', @Description='Nightclub', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'63', @LanguageCode='EN', @Description='Off-Site parking', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'64', @LanguageCode='EN', @Description='On-Site parking', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'65', @LanguageCode='EN', @Description='Outdoor parking', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'66', @LanguageCode='EN', @Description='Outdoor pool', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'67', @LanguageCode='EN', @Description='Package/Parcel services', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'68', @LanguageCode='EN', @Description='Parking', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'69', @LanguageCode='EN', @Description='Photocopy center', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'70', @LanguageCode='EN', @Description='Playground', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'71', @LanguageCode='EN', @Description='Pool', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'72', @LanguageCode='EN', @Description='Poolside snack bar', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'73', @LanguageCode='EN', @Description='Public address system', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'74', @LanguageCode='EN', @Description='Ramp access', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'75', @LanguageCode='EN', @Description='Recreational vehicle parking', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'76', @LanguageCode='EN', @Description='Restaurant', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'77', @LanguageCode='EN', @Description='Room service', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'78', @LanguageCode='EN', @Description='Safe deposit box', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'79', @LanguageCode='EN', @Description='Sauna', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'80', @LanguageCode='EN', @Description='Security', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'81', @LanguageCode='EN', @Description='Shoe shine stand', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'82', @LanguageCode='EN', @Description='Shopping mall', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'83', @LanguageCode='EN', @Description='Solarium', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'84', @LanguageCode='EN', @Description='Spa', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'85', @LanguageCode='EN', @Description='Sports bar', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'86', @LanguageCode='EN', @Description='Steam bath', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'87', @LanguageCode='EN', @Description='Storage space', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'88', @LanguageCode='EN', @Description='Sundry/Convenience store', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'89', @LanguageCode='EN', @Description='Technical concierge', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'90', @LanguageCode='EN', @Description='Theatre desk', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'91', @LanguageCode='EN', @Description='Tour/sightseeing desk', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'92', @LanguageCode='EN', @Description='Translation services', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'93', @LanguageCode='EN', @Description='Travel agency', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'94', @LanguageCode='EN', @Description='Truck parking', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'95', @LanguageCode='EN', @Description='Valet cleaning', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'96', @LanguageCode='EN', @Description='Dry cleaning', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'97', @LanguageCode='EN', @Description='Valet parking ', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'98', @LanguageCode='EN', @Description='Vending machines', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'99', @LanguageCode='EN', @Description='Video tapes', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'100', @LanguageCode='EN', @Description='Wakeup service', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'101', @LanguageCode='EN', @Description='Wheel chair access', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'102', @LanguageCode='EN', @Description='Whirlpool', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'103', @LanguageCode='EN', @Description='Multilingual staff', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'104', @LanguageCode='EN', @Description='Wedding services', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'105', @LanguageCode='EN', @Description='Banquet facilities', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'106', @LanguageCode='EN', @Description='Bell staff/porter', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'107', @LanguageCode='EN', @Description='Beauty shop/salon', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'108', @LanguageCode='EN', @Description='Complimentary self service laundry', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'109', @LanguageCode='EN', @Description='Direct dial telephone', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'110', @LanguageCode='EN', @Description='Female traveler room/floor', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'111', @LanguageCode='EN', @Description='Pharmacy', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'112', @LanguageCode='EN', @Description='Stables', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'113', @LanguageCode='EN', @Description='120 AC', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'114', @LanguageCode='EN', @Description='120 DC', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'115', @LanguageCode='EN', @Description='220 AC', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'116', @LanguageCode='EN', @Description='Accessible parking', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'117', @LanguageCode='EN', @Description='220 DC', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'118', @LanguageCode='EN', @Description='Barbeque grills', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'119', @LanguageCode='EN', @Description='Womens clothing', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'120', @LanguageCode='EN', @Description='Mens clothing', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'121', @LanguageCode='EN', @Description='Childrens clothing', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'122', @LanguageCode='EN', @Description='Shops and commercial services', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'123', @LanguageCode='EN', @Description='Video games', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'124', @LanguageCode='EN', @Description='Sports bar open for lunch', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'125', @LanguageCode='EN', @Description='Sports bar open for dinner', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'126', @LanguageCode='EN', @Description='Room service - full menu', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'127', @LanguageCode='EN', @Description='Room service - limited menu', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'128', @LanguageCode='EN', @Description='Room service - limited hours', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'129', @LanguageCode='EN', @Description='Valet same day dry cleaning', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'130', @LanguageCode='EN', @Description='Body scrub', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'131', @LanguageCode='EN', @Description='Body wrap', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'132', @LanguageCode='EN', @Description='Public area air conditioned', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'133', @LanguageCode='EN', @Description='Efolio available to company', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'134', @LanguageCode='EN', @Description='Individual Efolio available', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'135', @LanguageCode='EN', @Description='Video review billing', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'136', @LanguageCode='EN', @Description='Butler service', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'137', @LanguageCode='EN', @Description='Complimentary in-room coffee or tea', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'138', @LanguageCode='EN', @Description='Complimentary buffet breakfast', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'139', @LanguageCode='EN', @Description='Complimentary cocktails', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'140', @LanguageCode='EN', @Description='Complimentary coffee in lobby', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'141', @LanguageCode='EN', @Description='Complimentary continental breakfast', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'142', @LanguageCode='EN', @Description='Complimentary full american breakfast', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'143', @LanguageCode='EN', @Description='Dinner delivery service from local restaurant', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'144', @LanguageCode='EN', @Description='Complimentary newspaper delivered to room', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'145', @LanguageCode='EN', @Description='Complimentary newspaper in lobby', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'146', @LanguageCode='EN', @Description='Complimentary shoeshine', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'147', @LanguageCode='EN', @Description='Evening reception', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'148', @LanguageCode='EN', @Description='Front desk', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'149', @LanguageCode='EN', @Description='Grocery shopping service available', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'150', @LanguageCode='EN', @Description='Halal food available', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'151', @LanguageCode='EN', @Description='Kosher food available', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'152', @LanguageCode='EN', @Description='Limousine service', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'153', @LanguageCode='EN', @Description='Managers reception', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'154', @LanguageCode='EN', @Description='Medical Facilities Service', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'155', @LanguageCode='EN', @Description='Telephone jack adaptor available', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'156', @LanguageCode='EN', @Description='All-inclusive meal plan ', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'157', @LanguageCode='EN', @Description='Buffet breakfast', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'158', @LanguageCode='EN', @Description='Communal bar area', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'159', @LanguageCode='EN', @Description='Continental breakfast', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'160', @LanguageCode='EN', @Description='Full meal plan', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'161', @LanguageCode='EN', @Description='Full american breakfast', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'162', @LanguageCode='EN', @Description='Meal plan available', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'163', @LanguageCode='EN', @Description='Modified american meal plan', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'164', @LanguageCode='EN', @Description='Food and beverage outlets', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'165', @LanguageCode='EN', @Description='Lounges/bars', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'166', @LanguageCode='EN', @Description='Barber shop', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'167', @LanguageCode='EN', @Description='Video checkout', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'168', @LanguageCode='EN', @Description='Onsite laundry', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'169', @LanguageCode='EN', @Description='24-hour food & beverage kiosk', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'170', @LanguageCode='EN', @Description='Concierge lounge', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'171', @LanguageCode='EN', @Description='Parking fee managed by hotel', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'172', @LanguageCode='EN', @Description='Transportation', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'173', @LanguageCode='EN', @Description='Breakfast served in restaurant', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'174', @LanguageCode='EN', @Description='Lunch served in restaurant', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'175', @LanguageCode='EN', @Description='Dinner served in restaurant', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'176', @LanguageCode='EN', @Description='Full service housekeeping', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'177', @LanguageCode='EN', @Description='Limited service housekeeping', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'178', @LanguageCode='EN', @Description='High speed internet access for laptop in public areas', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'179', @LanguageCode='EN', @Description='Wireless internet connection in public areas', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'180', @LanguageCode='EN', @Description='Additional services/amenities/facilities on property', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'181', @LanguageCode='EN', @Description='Transportation services - local area', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'182', @LanguageCode='EN', @Description='Transportation services - local office', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'183', @LanguageCode='EN', @Description='DVD/video rental', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'184', @LanguageCode='EN', @Description='Parking lot', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'185', @LanguageCode='EN', @Description='Parking deck', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'186', @LanguageCode='EN', @Description='Street side parking', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'187', @LanguageCode='EN', @Description='Cocktail lounge with entertainment', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'188', @LanguageCode='EN', @Description='Cocktail lounge with light fare', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'189', @LanguageCode='EN', @Description='Motorcycle parking', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'190', @LanguageCode='EN', @Description='Phone services', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'191', @LanguageCode='EN', @Description='Ballroom', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'192', @LanguageCode='EN', @Description='Bus parking', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'193', @LanguageCode='EN', @Description='Childrens play area', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'194', @LanguageCode='EN', @Description='Childrens nursery', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'195', @LanguageCode='EN', @Description='Disco', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'196', @LanguageCode='EN', @Description='Early check-in', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'197', @LanguageCode='EN', @Description='Locker room', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'198', @LanguageCode='EN', @Description='Non-smoking rooms (generic)', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'199', @LanguageCode='EN', @Description='Train access', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'200', @LanguageCode='EN', @Description='Aerobics instruction', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'201', @LanguageCode='EN', @Description='Baggage hold', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'202', @LanguageCode='EN', @Description='Bicycle rentals', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'203', @LanguageCode='EN', @Description='Dietician', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'204', @LanguageCode='EN', @Description='Late check-out available', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'205', @LanguageCode='EN', @Description='Pet-sitting services', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'206', @LanguageCode='EN', @Description='Prayer mats', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'207', @LanguageCode='EN', @Description='Sports trainer', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'208', @LanguageCode='EN', @Description='Turndown service', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'209', @LanguageCode='EN', @Description='DVDs/videos - children', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'210', @LanguageCode='EN', @Description='Bank', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'211', @LanguageCode='EN', @Description='Lobby coffee service', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'212', @LanguageCode='EN', @Description='Banking services', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'213', @LanguageCode='EN', @Description='Stairwells', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'214', @LanguageCode='EN', @Description='Pet amenities available', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'215', @LanguageCode='EN', @Description='Exhibition/convention floor', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'216', @LanguageCode='EN', @Description='Long term parking', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'217', @LanguageCode='EN', @Description='Children not allowed', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'218', @LanguageCode='EN', @Description='Children welcome', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'219', @LanguageCode='EN', @Description='Courtesy car', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'220', @LanguageCode='EN', @Description='Hotel does not provide pornographic films/TV', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'221', @LanguageCode='EN', @Description='Hotspots', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'222', @LanguageCode='EN', @Description='Free high speed internet connection', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'223', @LanguageCode='EN', @Description='Internet services', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'224', @LanguageCode='EN', @Description='Pets allowed', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'225', @LanguageCode='EN', @Description='Gourmet highlights', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'226', @LanguageCode='EN', @Description='Catering services', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'227', @LanguageCode='EN', @Description='Complimentary breakfast', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'228', @LanguageCode='EN', @Description='Business center', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'229', @LanguageCode='EN', @Description='Business services', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'230', @LanguageCode='EN', @Description='Secured parking', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'231', @LanguageCode='EN', @Description='Racquetball', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'232', @LanguageCode='EN', @Description='Snow sports', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'233', @LanguageCode='EN', @Description='Tennis court', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'234', @LanguageCode='EN', @Description='Water sports', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'235', @LanguageCode='EN', @Description='Child programs', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'236', @LanguageCode='EN', @Description='Golf', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'237', @LanguageCode='EN', @Description='Horseback riding', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'238', @LanguageCode='EN', @Description='Oceanfront', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'239', @LanguageCode='EN', @Description='Beachfront', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'240', @LanguageCode='EN', @Description='Hair dryer', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'241', @LanguageCode='EN', @Description='Ironing board', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'242', @LanguageCode='EN', @Description='Heated guest rooms', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'243', @LanguageCode='EN', @Description='Toilet', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'244', @LanguageCode='EN', @Description='Parlor', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'245', @LanguageCode='EN', @Description='Video game player', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'246', @LanguageCode='EN', @Description='Thalassatherapy', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'247', @LanguageCode='EN', @Description='Private dining for groups', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'248', @LanguageCode='EN', @Description='Hearing impaired services', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'249', @LanguageCode='EN', @Description='Carryout breakfast', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'250', @LanguageCode='EN', @Description='Deluxe continental breakfast', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'251', @LanguageCode='EN', @Description='Hot continental breakfast', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'252', @LanguageCode='EN', @Description='Hot breakfast', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'253', @LanguageCode='EN', @Description='Private pool', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'254', @LanguageCode='EN', @Description='Connecting rooms', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'255', @LanguageCode='EN', @Description='Data port', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'256', @LanguageCode='EN', @Description='Exterior corridors', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'257', @LanguageCode='EN', @Description='Gulf view', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'258', @LanguageCode='EN', @Description='Handicap rooms', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'259', @LanguageCode='EN', @Description='High speed internet access', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'260', @LanguageCode='EN', @Description='Interior corridors', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'261', @LanguageCode='EN', @Description='High speed wireless', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'262', @LanguageCode='EN', @Description='Kitchenette', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'263', @LanguageCode='EN', @Description='Private bath or shower', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'264', @LanguageCode='EN', @Description='Fire safety compliant', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'265', @LanguageCode='EN', @Description='Welcome drink', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'266', @LanguageCode='EN', @Description='Boarding pass print-out available', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'267', @LanguageCode='EN', @Description='Printing services available', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'268', @LanguageCode='EN', @Description='All public areas non-smoking', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'269', @LanguageCode='EN', @Description='Meeting rooms', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'270', @LanguageCode='EN', @Description='Movies in room', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'271', @LanguageCode='EN', @Description='Secretarial service', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'272', @LanguageCode='EN', @Description='Snow skiing', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'273', @LanguageCode='EN', @Description='Water skiing', @BBImpTypeId='2'
EXEC [dbo].[ta_spp_InsertBedBankAmenity] @Code = N'274', @LanguageCode='EN', @Description='Fax service', @BBImpTypeId='2'
